name: Build SunamoGetFolders

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoGetFolders
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGetFolders/SunamoGetFolders.csproj

    - name: Build
      run: dotnet build SunamoGetFolders/SunamoGetFolders.csproj --configuration Release --no-restore

  test:
    name: Test SunamoGetFolders.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGetFolders.Tests/SunamoGetFolders.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoGetFolders.Tests/SunamoGetFolders.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoGetFolders.Tests/SunamoGetFolders.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
